//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class cabeceras {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cabeceras() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.cabeceras", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        internal static string _cabAccion {
            get {
                return ResourceManager.GetString("_cabAccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ap. Materno.
        /// </summary>
        internal static string _cabApMaterno {
            get {
                return ResourceManager.GetString("_cabApMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ap. Paterno.
        /// </summary>
        internal static string _cabApPaterno {
            get {
                return ResourceManager.GetString("_cabApPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string _cabArea {
            get {
                return ResourceManager.GetString("_cabArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area curso.
        /// </summary>
        internal static string _cabAreaCurso {
            get {
                return ResourceManager.GetString("_cabAreaCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificar.
        /// </summary>
        internal static string _cabCalificar {
            get {
                return ResourceManager.GetString("_cabCalificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant. Asignaciones.
        /// </summary>
        internal static string _cabCantAsignaciones {
            get {
                return ResourceManager.GetString("_cabCantAsignaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        internal static string _cabCargo {
            get {
                return ResourceManager.GetString("_cabCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string _cabCodigo {
            get {
                return ResourceManager.GetString("_cabCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario.
        /// </summary>
        internal static string _cabComentario {
            get {
                return ResourceManager.GetString("_cabComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string _cabDescripcion {
            get {
                return ResourceManager.GetString("_cabDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string _cabEmail {
            get {
                return ResourceManager.GetString("_cabEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string _cabEstado {
            get {
                return ResourceManager.GetString("_cabEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluación.
        /// </summary>
        internal static string _cabEvaluacion {
            get {
                return ResourceManager.GetString("_cabEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluador.
        /// </summary>
        internal static string _cabEvaluador {
            get {
                return ResourceManager.GetString("_cabEvaluador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluar.
        /// </summary>
        internal static string _cabEvaluar {
            get {
                return ResourceManager.GetString("_cabEvaluar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string _cabFecha {
            get {
                return ResourceManager.GetString("_cabFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha bitácora.
        /// </summary>
        internal static string _cabFechaBitacora {
            get {
                return ResourceManager.GetString("_cabFechaBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver ficha.
        /// </summary>
        internal static string _cabFicha {
            get {
                return ResourceManager.GetString("_cabFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        internal static string _cabFin {
            get {
                return ResourceManager.GetString("_cabFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerencia.
        /// </summary>
        internal static string _cabGerencia {
            get {
                return ResourceManager.GetString("_cabGerencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string _cabInicio {
            get {
                return ResourceManager.GetString("_cabInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla.
        /// </summary>
        internal static string _cabInstrumento {
            get {
                return ResourceManager.GetString("_cabInstrumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jefe.
        /// </summary>
        internal static string _cabJefe {
            get {
                return ResourceManager.GetString("_cabJefe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidad.
        /// </summary>
        internal static string _cabModalidad {
            get {
                return ResourceManager.GetString("_cabModalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        internal static string _cabNombre {
            get {
                return ResourceManager.GetString("_cabNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre curso.
        /// </summary>
        internal static string _cabNombreCurso {
            get {
                return ResourceManager.GetString("_cabNombreCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre usuario.
        /// </summary>
        internal static string _cabNombreUsuario {
            get {
                return ResourceManager.GetString("_cabNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoevaluación.
        /// </summary>
        internal static string _cabNotaAutoeval {
            get {
                return ResourceManager.GetString("_cabNotaAutoeval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Autoevaluación.
        /// </summary>
        internal static string _cabNotaAutoevaluacion {
            get {
                return ResourceManager.GetString("_cabNotaAutoevaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaboradores.
        /// </summary>
        internal static string _cabNotaColab {
            get {
                return ResourceManager.GetString("_cabNotaColab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Colaboradores.
        /// </summary>
        internal static string _cabNotaColaboradores {
            get {
                return ResourceManager.GetString("_cabNotaColaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota final.
        /// </summary>
        internal static string _cabNotaFinal {
            get {
                return ResourceManager.GetString("_cabNotaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Jefe.
        /// </summary>
        internal static string _cabNotaJefe {
            get {
                return ResourceManager.GetString("_cabNotaJefe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jefatura.
        /// </summary>
        internal static string _cabNotaJefes {
            get {
                return ResourceManager.GetString("_cabNotaJefes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pares.
        /// </summary>
        internal static string _cabNotaPar {
            get {
                return ResourceManager.GetString("_cabNotaPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Pares.
        /// </summary>
        internal static string _cabNotaPares {
            get {
                return ResourceManager.GetString("_cabNotaPares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponderación.
        /// </summary>
        internal static string _cabPonderacion {
            get {
                return ResourceManager.GetString("_cabPonderacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items a Evaluar.
        /// </summary>
        internal static string _cabPregunta {
            get {
                return ResourceManager.GetString("_cabPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relación.
        /// </summary>
        internal static string _cabRelacion {
            get {
                return ResourceManager.GetString("_cabRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        internal static string _cabResultado {
            get {
                return ResourceManager.GetString("_cabResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rut.
        /// </summary>
        internal static string _cabRut {
            get {
                return ResourceManager.GetString("_cabRut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rut usuario.
        /// </summary>
        internal static string _cabRutUsuario {
            get {
                return ResourceManager.GetString("_cabRutUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección.
        /// </summary>
        internal static string _cabSeccion {
            get {
                return ResourceManager.GetString("_cabSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucursal.
        /// </summary>
        internal static string _cabSucursal {
            get {
                return ResourceManager.GetString("_cabSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo evaluación.
        /// </summary>
        internal static string _cabTipoEval {
            get {
                return ResourceManager.GetString("_cabTipoEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        internal static string _cabValor {
            get {
                return ResourceManager.GetString("_cabValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Mayor.
        /// </summary>
        internal static string _cabValorMayor {
            get {
                return ResourceManager.GetString("_cabValorMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Menor.
        /// </summary>
        internal static string _cabValorMenor {
            get {
                return ResourceManager.GetString("_cabValorMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        internal static string _cabVer {
            get {
                return ResourceManager.GetString("_cabVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visador.
        /// </summary>
        internal static string _cabVisador {
            get {
                return ResourceManager.GetString("_cabVisador", resourceCulture);
            }
        }
    }
}
