//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class etiquetas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal etiquetas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.etiquetas", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: La clave ingresada no es valida..
        /// </summary>
        internal static string _alertClaveNoValida {
            get {
                return ResourceManager.GetString("_alertClaveNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: Los datos ingresados no son validos..
        /// </summary>
        internal static string _alertDatosNoValidos {
            get {
                return ResourceManager.GetString("_alertDatosNoValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: El Rut ingresado no es valido..
        /// </summary>
        internal static string _alertRutNoValido {
            get {
                return ResourceManager.GetString("_alertRutNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: El usuario ingresado no es valido..
        /// </summary>
        internal static string _alertUsuarioNoValido {
            get {
                return ResourceManager.GetString("_alertUsuarioNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción Pregunta.
        /// </summary>
        internal static string _etiAccionPregunta {
            get {
                return ResourceManager.GetString("_etiAccionPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string _etiAceptar {
            get {
                return ResourceManager.GetString("_etiAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string _etiActivo {
            get {
                return ResourceManager.GetString("_etiActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        internal static string _etiActualizar {
            get {
                return ResourceManager.GetString("_etiActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuerdo.
        /// </summary>
        internal static string _etiAcuerdo {
            get {
                return ResourceManager.GetString("_etiAcuerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmado por Evaluado.
        /// </summary>
        internal static string _etiAcuerdoEvaluado {
            get {
                return ResourceManager.GetString("_etiAcuerdoEvaluado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmado por Evaluador.
        /// </summary>
        internal static string _etiAcuerdoEvaluador {
            get {
                return ResourceManager.GetString("_etiAcuerdoEvaluador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta acción realizara cambios en los registros. ¿Desea continuar?.
        /// </summary>
        internal static string _etiAdvertencia {
            get {
                return ResourceManager.GetString("_etiAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario final.
        /// </summary>
        internal static string _etiAgregarComentario {
            get {
                return ResourceManager.GetString("_etiAgregarComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        internal static string _etiAgregarPregunta {
            get {
                return ResourceManager.GetString("_etiAgregarPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar sección manualmente.
        /// </summary>
        internal static string _etiAgregarSeccion {
            get {
                return ResourceManager.GetString("_etiAgregarSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Seleccionados.
        /// </summary>
        internal static string _etiAgregarSeleccionados {
            get {
                return ResourceManager.GetString("_etiAgregarSeleccionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Todos.
        /// </summary>
        internal static string _etiAgregarTodos {
            get {
                return ResourceManager.GetString("_etiAgregarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con apelación.
        /// </summary>
        internal static string _etiApelacion {
            get {
                return ResourceManager.GetString("_etiApelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelar.
        /// </summary>
        internal static string _etiApelar {
            get {
                return ResourceManager.GetString("_etiApelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar Fechas.
        /// </summary>
        internal static string _etiAplicarFechas {
            get {
                return ResourceManager.GetString("_etiAplicarFechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Materno.
        /// </summary>
        internal static string _etiApMaterno {
            get {
                return ResourceManager.GetString("_etiApMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido Paterno.
        /// </summary>
        internal static string _etiApPaterno {
            get {
                return ResourceManager.GetString("_etiApPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área.
        /// </summary>
        internal static string _etiArea {
            get {
                return ResourceManager.GetString("_etiArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Curso.
        /// </summary>
        internal static string _etiAreaCurso {
            get {
                return ResourceManager.GetString("_etiAreaCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignadas.
        /// </summary>
        internal static string _etiAsignadas {
            get {
                return ResourceManager.GetString("_etiAsignadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignados.
        /// </summary>
        internal static string _etiAsignados {
            get {
                return ResourceManager.GetString("_etiAsignados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        internal static string _etiAsunto {
            get {
                return ResourceManager.GetString("_etiAsunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoevaluación.
        /// </summary>
        internal static string _etiAutoevaluacion {
            get {
                return ResourceManager.GetString("_etiAutoevaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver bitácora.
        /// </summary>
        internal static string _etiBitacora {
            get {
                return ResourceManager.GetString("_etiBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar Borrador.
        /// </summary>
        internal static string _etiBorrador {
            get {
                return ResourceManager.GetString("_etiBorrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string _etiBuscar {
            get {
                return ResourceManager.GetString("_etiBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        internal static string _etiCargar {
            get {
                return ResourceManager.GetString("_etiCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        internal static string _etiCargo {
            get {
                return ResourceManager.GetString("_etiCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo Contacto.
        /// </summary>
        internal static string _etiCargoContacto {
            get {
                return ResourceManager.GetString("_etiCargoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATENCION: Ha ocurrido un error, revise la información ingresada y vuelva a intentar.
        ///En caso de persistir el problema, comunicarse con el administrador de la plataforma..
        /// </summary>
        internal static string _etiCatchError {
            get {
                return ResourceManager.GetString("_etiCatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias.
        /// </summary>
        internal static string _etiCategorias {
            get {
                return ResourceManager.GetString("_etiCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de costo.
        /// </summary>
        internal static string _etiCentroCosto {
            get {
                return ResourceManager.GetString("_etiCentroCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizadas.
        /// </summary>
        internal static string _etiCerradas {
            get {
                return ResourceManager.GetString("_etiCerradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string _etiCerrar {
            get {
                return ResourceManager.GetString("_etiCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar evaluación.
        /// </summary>
        internal static string _etiCerrarEvaluacion {
            get {
                return ResourceManager.GetString("_etiCerrarEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificador 1.
        /// </summary>
        internal static string _etiClasificador1 {
            get {
                return ResourceManager.GetString("_etiClasificador1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clasificador 2.
        /// </summary>
        internal static string _etiClasificador2 {
            get {
                return ResourceManager.GetString("_etiClasificador2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string _etiCodigo {
            get {
                return ResourceManager.GetString("_etiCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaboradores.
        /// </summary>
        internal static string _etiColaboradores {
            get {
                return ResourceManager.GetString("_etiColaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario Feedback.
        /// </summary>
        internal static string _etiComentarioFeedback {
            get {
                return ResourceManager.GetString("_etiComentarioFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compromiso.
        /// </summary>
        internal static string _etiCompromiso {
            get {
                return ResourceManager.GetString("_etiCompromiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compromiso Pregunta.
        /// </summary>
        internal static string _etiCompromisoPregunta {
            get {
                return ResourceManager.GetString("_etiCompromisoPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con calibración.
        /// </summary>
        internal static string _etiConCalibracion {
            get {
                return ResourceManager.GetString("_etiConCalibracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingreso de objetivos.
        /// </summary>
        internal static string _etiConObservaciones {
            get {
                return ResourceManager.GetString("_etiConObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        internal static string _etiConsultar {
            get {
                return ResourceManager.GetString("_etiConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        internal static string _etiContinuar {
            get {
                return ResourceManager.GetString("_etiContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string _etiContinuarNo {
            get {
                return ResourceManager.GetString("_etiContinuarNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        internal static string _etiContinuarSi {
            get {
                return ResourceManager.GetString("_etiContinuarSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string _etiContrasena {
            get {
                return ResourceManager.GetString("_etiContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuerpo correo.
        /// </summary>
        internal static string _etiCuerpoCorreo {
            get {
                return ResourceManager.GetString("_etiCuerpoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaro haber sido informado de los resultados de mi evaluación de competencias y del plan de desarrollo correspondiente..
        /// </summary>
        internal static string _etiDeclaracion {
            get {
                return ResourceManager.GetString("_etiDeclaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        internal static string _etiDescargar {
            get {
                return ResourceManager.GetString("_etiDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar Consolidado.
        /// </summary>
        internal static string _etiDescargarConsolidado {
            get {
                return ResourceManager.GetString("_etiDescargarConsolidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar Detalle.
        /// </summary>
        internal static string _etiDescargarDetalle {
            get {
                return ResourceManager.GetString("_etiDescargarDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar formato.
        /// </summary>
        internal static string _etiDescargarFormato {
            get {
                return ResourceManager.GetString("_etiDescargarFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string _etiDescripcion {
            get {
                return ResourceManager.GetString("_etiDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción Plantilla.
        /// </summary>
        internal static string _etiDescripcionInstrumento {
            get {
                return ResourceManager.GetString("_etiDescripcionInstrumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción Pregunta.
        /// </summary>
        internal static string _etiDescripcionPregunta {
            get {
                return ResourceManager.GetString("_etiDescripcionPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion Sección.
        /// </summary>
        internal static string _etiDescripcionSeccion {
            get {
                return ResourceManager.GetString("_etiDescripcionSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseleccionar Todos.
        /// </summary>
        internal static string _etiDeselecTodos {
            get {
                return ResourceManager.GetString("_etiDeselecTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuestas de desempeño.
        /// </summary>
        internal static string _etiDesempeno {
            get {
                return ResourceManager.GetString("_etiDesempeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle apelación.
        /// </summary>
        internal static string _etiDetalleApelacion {
            get {
                return ResourceManager.GetString("_etiDetalleApelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string _etiDirecciónEval {
            get {
                return ResourceManager.GetString("_etiDirecciónEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponibles.
        /// </summary>
        internal static string _etiDisponibles {
            get {
                return ResourceManager.GetString("_etiDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominio.
        /// </summary>
        internal static string _etiDominio {
            get {
                return ResourceManager.GetString("_etiDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string _etiEditar {
            get {
                return ResourceManager.GetString("_etiEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string _etiEliminar {
            get {
                return ResourceManager.GetString("_etiEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string _etiEmail {
            get {
                return ResourceManager.GetString("_etiEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Contacto.
        /// </summary>
        internal static string _etiEmailContacto {
            get {
                return ResourceManager.GetString("_etiEmailContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string _etiEmpresa {
            get {
                return ResourceManager.GetString("_etiEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En apelación.
        /// </summary>
        internal static string _etiEnApelacion {
            get {
                return ResourceManager.GetString("_etiEnApelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En proceso.
        /// </summary>
        internal static string _etiEnBorrador {
            get {
                return ResourceManager.GetString("_etiEnBorrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Feedback.
        /// </summary>
        internal static string _etiEnFeedback {
            get {
                return ResourceManager.GetString("_etiEnFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string _etiEnviar {
            get {
                return ResourceManager.GetString("_etiEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: Ha ocurrido un error en el proceso..
        /// </summary>
        internal static string _etiError {
            get {
                return ResourceManager.GetString("_etiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: No es posible realizar esta acción, ya que los datos que desea eliminar posee información asociada..
        /// </summary>
        internal static string _etiErrorDatosRelacionados {
            get {
                return ResourceManager.GetString("_etiErrorDatosRelacionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La suma de la ponderación debe ser de 100..
        /// </summary>
        internal static string _etiErrorPonderacion {
            get {
                return ResourceManager.GetString("_etiErrorPonderacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: Los valores ingresados no deben salir del rango de evaluación..
        /// </summary>
        internal static string _etiErrorRango {
            get {
                return ResourceManager.GetString("_etiErrorRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ingresar un comentario en las competencias evaluadas con la nota mínima o máxima de la escala..
        /// </summary>
        internal static string _etiErrorSinComentario {
            get {
                return ResourceManager.GetString("_etiErrorSinComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención: Debe ingresar todos los valores solicitados..
        /// </summary>
        internal static string _etiErrorVacios {
            get {
                return ResourceManager.GetString("_etiErrorVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escala.
        /// </summary>
        internal static string _etiEscala {
            get {
                return ResourceManager.GetString("_etiEscala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluado.
        /// </summary>
        internal static string _etiEvaluado {
            get {
                return ResourceManager.GetString("_etiEvaluado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluador.
        /// </summary>
        internal static string _etiEvaluador {
            get {
                return ResourceManager.GetString("_etiEvaluador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluar.
        /// </summary>
        internal static string _etiEvaluar {
            get {
                return ResourceManager.GetString("_etiEvaluar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso ha finalizado exitosamente..
        /// </summary>
        internal static string _etiExito {
            get {
                return ResourceManager.GetString("_etiExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        internal static string _etiFin {
            get {
                return ResourceManager.GetString("_etiFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activa.
        /// </summary>
        internal static string _etiFlagActiva {
            get {
                return ResourceManager.GetString("_etiFlagActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fono.
        /// </summary>
        internal static string _etiFonoContacto {
            get {
                return ResourceManager.GetString("_etiFonoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerencia.
        /// </summary>
        internal static string _etiGerencia {
            get {
                return ResourceManager.GetString("_etiGerencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giro.
        /// </summary>
        internal static string _etiGiro {
            get {
                return ResourceManager.GetString("_etiGiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grados.
        /// </summary>
        internal static string _etiGrado {
            get {
                return ResourceManager.GetString("_etiGrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string _etiGuardar {
            get {
                return ResourceManager.GetString("_etiGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoja de Vida.
        /// </summary>
        internal static string _etiHojaDeVida {
            get {
                return ResourceManager.GetString("_etiHojaDeVida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicador Pregunta.
        /// </summary>
        internal static string _etiIndicadorPregunta {
            get {
                return ResourceManager.GetString("_etiIndicadorPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informadas.
        /// </summary>
        internal static string _etiInformadas {
            get {
                return ResourceManager.GetString("_etiInformadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informar.
        /// </summary>
        internal static string _etiInformar {
            get {
                return ResourceManager.GetString("_etiInformar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string _etiInicio {
            get {
                return ResourceManager.GetString("_etiInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrucciones.
        /// </summary>
        internal static string _etiInstrucciones {
            get {
                return ResourceManager.GetString("_etiInstrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla de Evaluación.
        /// </summary>
        internal static string _etiInstrumento {
            get {
                return ResourceManager.GetString("_etiInstrumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        internal static string _etiIrTodos {
            get {
                return ResourceManager.GetString("_etiIrTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string _etiIrUno {
            get {
                return ResourceManager.GetString("_etiIrUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jefaturas.
        /// </summary>
        internal static string _etiJefaturas {
            get {
                return ResourceManager.GetString("_etiJefaturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI.
        /// </summary>
        internal static string _etiKPI {
            get {
                return ResourceManager.GetString("_etiKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI Vigente.
        /// </summary>
        internal static string _etiKPIVigente {
            get {
                return ResourceManager.GetString("_etiKPIVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis competencias.
        /// </summary>
        internal static string _etiMiDesempeno {
            get {
                return ResourceManager.GetString("_etiMiDesempeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi equipo.
        /// </summary>
        internal static string _etiMiEquipo {
            get {
                return ResourceManager.GetString("_etiMiEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluaciones en proceso.
        /// </summary>
        internal static string _etiMisColaboradores {
            get {
                return ResourceManager.GetString("_etiMisColaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi historial.
        /// </summary>
        internal static string _etiMisEvaluaciones {
            get {
                return ResourceManager.GetString("_etiMisEvaluaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis KPI.
        /// </summary>
        internal static string _etiMisKPI {
            get {
                return ResourceManager.GetString("_etiMisKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de visaciones.
        /// </summary>
        internal static string _etiMisVisaciones {
            get {
                return ResourceManager.GetString("_etiMisVisaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo de apelación.
        /// </summary>
        internal static string _etiMotivo {
            get {
                return ResourceManager.GetString("_etiMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string _etiNombre {
            get {
                return ResourceManager.GetString("_etiNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre asignación.
        /// </summary>
        internal static string _etiNombreAsignacion {
            get {
                return ResourceManager.GetString("_etiNombreAsignacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Clasificador 1.
        /// </summary>
        internal static string _etiNombreClasificador1 {
            get {
                return ResourceManager.GetString("_etiNombreClasificador1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Clasificador 2.
        /// </summary>
        internal static string _etiNombreClasificador2 {
            get {
                return ResourceManager.GetString("_etiNombreClasificador2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Contacto.
        /// </summary>
        internal static string _etiNombreContacto {
            get {
                return ResourceManager.GetString("_etiNombreContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Fantasía.
        /// </summary>
        internal static string _etiNombreFantasia {
            get {
                return ResourceManager.GetString("_etiNombreFantasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Plantilla.
        /// </summary>
        internal static string _etiNombreInstrumento {
            get {
                return ResourceManager.GetString("_etiNombreInstrumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Sección.
        /// </summary>
        internal static string _etiNombreSeccion {
            get {
                return ResourceManager.GetString("_etiNombreSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificar.
        /// </summary>
        internal static string _etiNotificar {
            get {
                return ResourceManager.GetString("_etiNotificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string _etiNuevo {
            get {
                return ResourceManager.GetString("_etiNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación.
        /// </summary>
        internal static string _etiObservacion {
            get {
                return ResourceManager.GetString("_etiObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación Plantilla.
        /// </summary>
        internal static string _etiObservacionInstrumento {
            get {
                return ResourceManager.GetString("_etiObservacionInstrumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        internal static string _etiOrdenSeccion {
            get {
                return ResourceManager.GetString("_etiOrdenSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pares.
        /// </summary>
        internal static string _etiPares {
            get {
                return ResourceManager.GetString("_etiPares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo para cargar asignaciones.
        /// </summary>
        internal static string _etiParesXLSFUL {
            get {
                return ResourceManager.GetString("_etiParesXLSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string _etiPassword {
            get {
                return ResourceManager.GetString("_etiPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitir agregar preguntas.
        /// </summary>
        internal static string _etiPermitirNuevasPreguntas {
            get {
                return ResourceManager.GetString("_etiPermitirNuevasPreguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de desarrollo.
        /// </summary>
        internal static string _etiPlanDesarrollo {
            get {
                return ResourceManager.GetString("_etiPlanDesarrollo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaboradores.
        /// </summary>
        internal static string _etiPondColaboradores {
            get {
                return ResourceManager.GetString("_etiPondColaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponderación.
        /// </summary>
        internal static string _etiPonderacionSeccion {
            get {
                return ResourceManager.GetString("_etiPonderacionSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoevaluación.
        /// </summary>
        internal static string _etiPondEutoEvaluacion {
            get {
                return ResourceManager.GetString("_etiPondEutoEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jefaturas.
        /// </summary>
        internal static string _etiPondJefaturas {
            get {
                return ResourceManager.GetString("_etiPondJefaturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pares.
        /// </summary>
        internal static string _etiPondPares {
            get {
                return ResourceManager.GetString("_etiPondPares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto.
        /// </summary>
        internal static string _etiPuerto {
            get {
                return ResourceManager.GetString("_etiPuerto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rangos de evaluacíon.
        /// </summary>
        internal static string _etiRangos {
            get {
                return ResourceManager.GetString("_etiRangos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón Social.
        /// </summary>
        internal static string _etiRazonSocial {
            get {
                return ResourceManager.GetString("_etiRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relación.
        /// </summary>
        internal static string _etiRelacion {
            get {
                return ResourceManager.GetString("_etiRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir Contraseña.
        /// </summary>
        internal static string _etiRepContrasena {
            get {
                return ResourceManager.GetString("_etiRepContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir Password.
        /// </summary>
        internal static string _etiRepetirPassword {
            get {
                return ResourceManager.GetString("_etiRepetirPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        internal static string _etiResultado {
            get {
                return ResourceManager.GetString("_etiResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        internal static string _etiRol {
            get {
                return ResourceManager.GetString("_etiRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rut.
        /// </summary>
        internal static string _etiRut {
            get {
                return ResourceManager.GetString("_etiRut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rut Jefe.
        /// </summary>
        internal static string _etiRutJefe {
            get {
                return ResourceManager.GetString("_etiRutJefe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visador.
        /// </summary>
        internal static string _etiRutVisador {
            get {
                return ResourceManager.GetString("_etiRutVisador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo para carga de secciones.
        /// </summary>
        internal static string _etiSeccionesXLSFUL {
            get {
                return ResourceManager.GetString("_etiSeccionesXLSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secciones (XLS).
        /// </summary>
        internal static string _etiSeccionesXLSTitulo {
            get {
                return ResourceManager.GetString("_etiSeccionesXLSTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Todos.
        /// </summary>
        internal static string _etiSelecTodos {
            get {
                return ResourceManager.GetString("_etiSelecTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMPT.
        /// </summary>
        internal static string _etiSMPT {
            get {
                return ResourceManager.GetString("_etiSMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucursal.
        /// </summary>
        internal static string _etiSucursal {
            get {
                return ResourceManager.GetString("_etiSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta.
        /// </summary>
        internal static string _etiTextoPregunta {
            get {
                return ResourceManager.GetString("_etiTextoPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Asignación.
        /// </summary>
        internal static string _etiTipoAsignacion {
            get {
                return ResourceManager.GetString("_etiTipoAsignacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo reporte.
        /// </summary>
        internal static string _etiTipoReporte {
            get {
                return ResourceManager.GetString("_etiTipoReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Sección.
        /// </summary>
        internal static string _etiTipoSeccion {
            get {
                return ResourceManager.GetString("_etiTipoSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomar conocimiento.
        /// </summary>
        internal static string _etiTomarConocimiento {
            get {
                return ResourceManager.GetString("_etiTomarConocimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL plataforma.
        /// </summary>
        internal static string _etiUrlPlataforma {
            get {
                return ResourceManager.GetString("_etiUrlPlataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string _etiUsuario {
            get {
                return ResourceManager.GetString("_etiUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo para cargar usuarios.
        /// </summary>
        internal static string _etiUsuariosXLSFUL {
            get {
                return ResourceManager.GetString("_etiUsuariosXLSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios (XLS).
        /// </summary>
        internal static string _etiUsuariosXLSTitulo {
            get {
                return ResourceManager.GetString("_etiUsuariosXLSTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor mayor.
        /// </summary>
        internal static string _etiValorMayor {
            get {
                return ResourceManager.GetString("_etiValorMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor menor.
        /// </summary>
        internal static string _etiValorMenor {
            get {
                return ResourceManager.GetString("_etiValorMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor rango.
        /// </summary>
        internal static string _etiValorRango {
            get {
                return ResourceManager.GetString("_etiValorRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver detalle.
        /// </summary>
        internal static string _etiVerDetalle {
            get {
                return ResourceManager.GetString("_etiVerDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver evaluación.
        /// </summary>
        internal static string _etiVerEvaluacion {
            get {
                return ResourceManager.GetString("_etiVerEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver ficha.
        /// </summary>
        internal static string _etiVerFicha {
            get {
                return ResourceManager.GetString("_etiVerFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver KPI.
        /// </summary>
        internal static string _etiVerKPI {
            get {
                return ResourceManager.GetString("_etiVerKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Con visación.
        /// </summary>
        internal static string _etiVisacion {
            get {
                return ResourceManager.GetString("_etiVisacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visadas.
        /// </summary>
        internal static string _etiVisadas {
            get {
                return ResourceManager.GetString("_etiVisadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visador.
        /// </summary>
        internal static string _etiVisador {
            get {
                return ResourceManager.GetString("_etiVisador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visar.
        /// </summary>
        internal static string _etiVisar {
            get {
                return ResourceManager.GetString("_etiVisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visar evaluación.
        /// </summary>
        internal static string _etiVisarEvaluacion {
            get {
                return ResourceManager.GetString("_etiVisarEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        internal static string _etiVolver {
            get {
                return ResourceManager.GetString("_etiVolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        internal static string _etiVolverTodos {
            get {
                return ResourceManager.GetString("_etiVolverTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string _etiVolverUno {
            get {
                return ResourceManager.GetString("_etiVolverUno", resourceCulture);
            }
        }
    }
}
