//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.menu", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Evaluaciones.
        /// </summary>
        internal static string _menuAdmAsignacion {
            get {
                return ResourceManager.GetString("_menuAdmAsignacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Pares.
        /// </summary>
        internal static string _menuAdmAsignacionPares {
            get {
                return ResourceManager.GetString("_menuAdmAsignacionPares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga Nomina de Personal.
        /// </summary>
        internal static string _menuAdmCargaUsuarios {
            get {
                return ResourceManager.GetString("_menuAdmCargaUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos.
        /// </summary>
        internal static string _menuAdmCursos {
            get {
                return ResourceManager.GetString("_menuAdmCursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresas.
        /// </summary>
        internal static string _menuAdmEmpresas {
            get {
                return ResourceManager.GetString("_menuAdmEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalas de Evaluación.
        /// </summary>
        internal static string _menuAdmEscala {
            get {
                return ResourceManager.GetString("_menuAdmEscala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla de Evaluación.
        /// </summary>
        internal static string _menuAdmEvaluacion {
            get {
                return ResourceManager.GetString("_menuAdmEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametros.
        /// </summary>
        internal static string _menuAdmParametros {
            get {
                return ResourceManager.GetString("_menuAdmParametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias de Seccion.
        /// </summary>
        internal static string _menuAdmTiposSeccion {
            get {
                return ResourceManager.GetString("_menuAdmTiposSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración.
        /// </summary>
        internal static string _menuAdmTitulo {
            get {
                return ResourceManager.GetString("_menuAdmTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        internal static string _menuAdmUsuario {
            get {
                return ResourceManager.GetString("_menuAdmUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparativa anual.
        /// </summary>
        internal static string _menuComparativaAnual {
            get {
                return ResourceManager.GetString("_menuComparativaAnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consola.
        /// </summary>
        internal static string _menuConsolaTitulo {
            get {
                return ResourceManager.GetString("_menuConsolaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Consolidado.
        /// </summary>
        internal static string _menuGestionConsolidado {
            get {
                return ResourceManager.GetString("_menuGestionConsolidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Evaluaciones.
        /// </summary>
        internal static string _menuGestionDetalleEvaluaciones {
            get {
                return ResourceManager.GetString("_menuGestionDetalleEvaluaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes e Indicadores.
        /// </summary>
        internal static string _menuGestionTitulo {
            get {
                return ResourceManager.GetString("_menuGestionTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string _menuSalir {
            get {
                return ResourceManager.GetString("_menuSalir", resourceCulture);
            }
        }
    }
}
