//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class titulos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal titulos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.titulos", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, usted no tiene acceso a esta sección. Ante cualquier duda debe contactarse con el administrador de esta plataforma..
        /// </summary>
        internal static string _alertSinAcceso {
            get {
                return ResourceManager.GetString("_alertSinAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El colaborador no presenta KPI en este periodo..
        /// </summary>
        internal static string _alertSinKPI {
            get {
                return ResourceManager.GetString("_alertSinKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        internal static string _etiAdvertencia {
            get {
                return ResourceManager.GetString("_etiAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string _etiEmail {
            get {
                return ResourceManager.GetString("_etiEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfiles.
        /// </summary>
        internal static string _etiPerfiles {
            get {
                return ResourceManager.GetString("_etiPerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización.
        /// </summary>
        internal static string _titActualizacion {
            get {
                return ResourceManager.GetString("_titActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Escalas de Evaluación.
        /// </summary>
        internal static string _titAdmEscala {
            get {
                return ResourceManager.GetString("_titAdmEscala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenedor de cursos.
        /// </summary>
        internal static string _titAdminCursos {
            get {
                return ResourceManager.GetString("_titAdminCursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración Empresas.
        /// </summary>
        internal static string _titAdminEmpresas {
            get {
                return ResourceManager.GetString("_titAdminEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Configuración de Evaluaciones.
        /// </summary>
        internal static string _titAdmInstrumentos {
            get {
                return ResourceManager.GetString("_titAdmInstrumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secciones.
        /// </summary>
        internal static string _titAdmInstrumentosSecciones {
            get {
                return ResourceManager.GetString("_titAdmInstrumentosSecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Sección.
        /// </summary>
        internal static string _titAdmInstrumentosSeccionPreguntas {
            get {
                return ResourceManager.GetString("_titAdmInstrumentosSeccionPreguntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Parametros.
        /// </summary>
        internal static string _titAdmParametros {
            get {
                return ResourceManager.GetString("_titAdmParametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Categorias de Secciones.
        /// </summary>
        internal static string _titAdmTipoSeccion {
            get {
                return ResourceManager.GetString("_titAdmTipoSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Usuarios.
        /// </summary>
        internal static string _titAdmUsuarios {
            get {
                return ResourceManager.GetString("_titAdmUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        internal static string _titAdvertencia {
            get {
                return ResourceManager.GetString("_titAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelar.
        /// </summary>
        internal static string _titApelar {
            get {
                return ResourceManager.GetString("_titApelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrativas.
        /// </summary>
        internal static string _titAreaAdministrativas {
            get {
                return ResourceManager.GetString("_titAreaAdministrativas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comerciales.
        /// </summary>
        internal static string _titAreaComerciales {
            get {
                return ResourceManager.GetString("_titAreaComerciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilidades Blandas.
        /// </summary>
        internal static string _titAreaHabilidadesBlandas {
            get {
                return ResourceManager.GetString("_titAreaHabilidadesBlandas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas.
        /// </summary>
        internal static string _titAreaIdiomas {
            get {
                return ResourceManager.GetString("_titAreaIdiomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mejora Continua.
        /// </summary>
        internal static string _titAreaMejoraContinua {
            get {
                return ResourceManager.GetString("_titAreaMejoraContinua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otras Capacitaciones.
        /// </summary>
        internal static string _titAreaOtrasCapacitaciones {
            get {
                return ResourceManager.GetString("_titAreaOtrasCapacitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producción.
        /// </summary>
        internal static string _titAreaRelativasProduccion {
            get {
                return ResourceManager.GetString("_titAreaRelativasProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguridad Industrial y Autocuidado.
        /// </summary>
        internal static string _titAreaSeguridad {
            get {
                return ResourceManager.GetString("_titAreaSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TI/Ofimatica.
        /// </summary>
        internal static string _titAreaTiOfimatica {
            get {
                return ResourceManager.GetString("_titAreaTiOfimatica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Evaluaciones.
        /// </summary>
        internal static string _titAsignarEvaluacion {
            get {
                return ResourceManager.GetString("_titAsignarEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Evaluaciones.
        /// </summary>
        internal static string _titAsignarEvaluacionPartners {
            get {
                return ResourceManager.GetString("_titAsignarEvaluacionPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitácora.
        /// </summary>
        internal static string _titBitacora {
            get {
                return ResourceManager.GetString("_titBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscador de Colaboradores.
        /// </summary>
        internal static string _titBuscadorColaboradores {
            get {
                return ResourceManager.GetString("_titBuscadorColaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos de capacitación.
        /// </summary>
        internal static string _titCapacitaciones {
            get {
                return ResourceManager.GetString("_titCapacitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carga Nomina de Personal.
        /// </summary>
        internal static string _titCargaNomina {
            get {
                return ResourceManager.GetString("_titCargaNomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaboradores.
        /// </summary>
        internal static string _titColaboradores {
            get {
                return ResourceManager.GetString("_titColaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos de capacitación.
        /// </summary>
        internal static string _titCursos {
            get {
                return ResourceManager.GetString("_titCursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string _titDashboard {
            get {
                return ResourceManager.GetString("_titDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Formulario de Evaluación.
        /// </summary>
        internal static string _titEdicionFormularios {
            get {
                return ResourceManager.GetString("_titEdicionFormularios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Formulario.
        /// </summary>
        internal static string _titEditarEvaluacion {
            get {
                return ResourceManager.GetString("_titEditarEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string _titError {
            get {
                return ResourceManager.GetString("_titError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar estado de asignación.
        /// </summary>
        internal static string _titEstadoAsignacion {
            get {
                return ResourceManager.GetString("_titEstadoAsignacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario de Evaluación.
        /// </summary>
        internal static string _titEvaluacion {
            get {
                return ResourceManager.GetString("_titEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exito.
        /// </summary>
        internal static string _titExito {
            get {
                return ResourceManager.GetString("_titExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha personal.
        /// </summary>
        internal static string _titFicha {
            get {
                return ResourceManager.GetString("_titFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario de evaluación.
        /// </summary>
        internal static string _titFormularioEvaluacion {
            get {
                return ResourceManager.GetString("_titFormularioEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Consolidado.
        /// </summary>
        internal static string _titGestionConsolidado {
            get {
                return ResourceManager.GetString("_titGestionConsolidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle Evaluaciones.
        /// </summary>
        internal static string _titGestionDetalle {
            get {
                return ResourceManager.GetString("_titGestionDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe Evaluación.
        /// </summary>
        internal static string _titInformeEvaluacion {
            get {
                return ResourceManager.GetString("_titInformeEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor de Items a Evaluar.
        /// </summary>
        internal static string _titMantPregunta {
            get {
                return ResourceManager.GetString("_titMantPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menú Principal.
        /// </summary>
        internal static string _titMenu {
            get {
                return ResourceManager.GetString("_titMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración.
        /// </summary>
        internal static string _titMenuAdministracion {
            get {
                return ResourceManager.GetString("_titMenuAdministracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consola.
        /// </summary>
        internal static string _titMenuConsola {
            get {
                return ResourceManager.GetString("_titMenuConsola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes e Indicadores.
        /// </summary>
        internal static string _titMenuGestion {
            get {
                return ResourceManager.GetString("_titMenuGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaciones.
        /// </summary>
        internal static string _titNotificaciones {
            get {
                return ResourceManager.GetString("_titNotificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetivos.
        /// </summary>
        internal static string _titObjetivosActuales {
            get {
                return ResourceManager.GetString("_titObjetivosActuales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetivos proximo periodo.
        /// </summary>
        internal static string _titObjetivosProximos {
            get {
                return ResourceManager.GetString("_titObjetivosProximos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones finales.
        /// </summary>
        internal static string _titObservacionesFinales {
            get {
                return ResourceManager.GetString("_titObservacionesFinales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar contraseña.
        /// </summary>
        internal static string _titOlvidoContrasena {
            get {
                return ResourceManager.GetString("_titOlvidoContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo5.
        /// </summary>
        internal static string _titPieParteDos {
            get {
                return ResourceManager.GetString("_titPieParteDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollado por - .
        /// </summary>
        internal static string _titPieParteUno {
            get {
                return ResourceManager.GetString("_titPieParteUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan de Desarrollo.
        /// </summary>
        internal static string _titPlanDesarrollo {
            get {
                return ResourceManager.GetString("_titPlanDesarrollo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponderaciones (%).
        /// </summary>
        internal static string _titPonderaciones {
            get {
                return ResourceManager.GetString("_titPonderaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toma de Conocimiento.
        /// </summary>
        internal static string _titTomaConocimiento {
            get {
                return ResourceManager.GetString("_titTomaConocimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Detalles.
        /// </summary>
        internal static string _titVerDetalles {
            get {
                return ResourceManager.GetString("_titVerDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visar evaluación.
        /// </summary>
        internal static string _titVisar {
            get {
                return ResourceManager.GetString("_titVisar", resourceCulture);
            }
        }
    }
}
